export function getStartData(){
    return [

        { top: '10%', left: '20%', classStart: 'star-1' },
        { top: '20%', left: '50%', classStart: 'star-1' },
        { top: '30%', left: '80%', classStart: 'star-2' },
        { top: '15%', left: '30%', classStart: 'star-1' },
        { top: '25%', left: '60%', classStart: 'star-2' },
        { top: '35%', left: '90%', classStart: 'star-3' },
        { top: '45%', left: '15%', classStart: 'star-3' },
        { top: '55%', left: '45%', classStart: 'star-3' },
        { top: '65%', left: '75%', classStart: 'star-2' },
        { top: '75%', left: '5%', classStart: 'star-1' },
        { top: '85%', left: '35%', classStart: 'star-2' },
        { top: '5%', left: '65%', classStart: 'star-2' },
        { top: '30%', left: '85%', classStart: 'star-1' },
        { top: '50%', left: '20%', classStart: 'star-1' },
        { top: '70%', left: '40%', classStart: 'star-1' },
        { top: '10%', left: '60%', classStart: 'star-2' },
        { top: '40%', left: '70%', classStart: 'star-2' },
        { top: '60%', left: '90%', classStart: 'star-1' },
        { top: '80%', left: '10%', classStart: 'star-1' },
        { top: '90%', left: '50%', classStart: 'star-3' },
        { top: '15%', left: '30%', classStart: 'star-1' },
        { top: '20%', left: '40%', classStart: 'star-2' },
        { top: '30%', left: '80%', classStart: 'star-2' },
        { top: '85%', left: '95%', classStart: 'star-1' },
        { top: '27%', left: '60%', classStart: 'star-1' },
        { top: '35%', left: '90%', classStart: 'star-3' },
        { top: '75%', left: '16%', classStart: 'star-3' },
        { top: '55%', left: '45%', classStart: 'star-3' },
        { top: '15%', left: '75%', classStart: 'star-3' },
        { top: '55%', left: '25%', classStart: 'star-1' },
        { top: '85%', left: '35%', classStart: 'star-1' },
        { top: '5%', left: '65%', classStart: 'star-2' },
        { top: '20%', left: '45%', classStart: 'star-1' },
        { top: '58%', left: '18%', classStart: 'star-1' },
        { top: '78%', left: '67%', classStart: 'star-3' },
        { top: '10%', left: '60%', classStart: 'star-3' },
        { top: '40%', left: '70%', classStart: 'star-2' },
        { top: '60%', left: '90%', classStart: 'star-2' },
        { top: '10%', left: '40%', classStart: 'star-1' },
        { top: '70%', left: '50%', classStart: 'star-2' },
        // Agrega aquí más estrellas con diferentes posiciones
      ]

}